[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "mlx-lm"
description = "LLMs with MLX and the Hugging Face Hub"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "MLX Contributors", email = "mlx@group.apple.com" }]
dynamic = ["version"]
dependencies = [
    "mlx>=0.31.2; platform_system == 'Darwin'",
    "numpy",
    "transformers>=5.0.0",
    "sentencepiece",
    "protobuf",
    "pyyaml",
    "jinja2",
]

[project.urls]
Homepage = "https://github.com/ml-explore/mlx-lm"
Repository = "https://github.com/ml-explore/mlx-lm"
Issues = "https://github.com/ml-explore/mlx-lm/issues"

[project.optional-dependencies]
test = ["datasets", "lm-eval"]
train = ["datasets", "tqdm"]
evaluate = ["lm-eval", "tqdm"]
cuda13 = ["mlx[cuda13]>=0.30.4"]
cuda12 = ["mlx[cuda12]>=0.30.4"]
cpu = ["mlx[cpu]>=0.30.4"]

[project.scripts]
mlx_lm = "mlx_lm.cli:main"
"mlx_lm.awq" = "mlx_lm.quant.awq:main"
"mlx_lm.dwq" = "mlx_lm.quant.dwq:main"
"mlx_lm.dynamic_quant" = "mlx_lm.quant.dynamic_quant:main"
"mlx_lm.gptq" = "mlx_lm.quant.gptq:main"
"mlx_lm.benchmark" = "mlx_lm.benchmark:main"
"mlx_lm.cache_prompt" = "mlx_lm.cache_prompt:main"
"mlx_lm.chat" = "mlx_lm.chat:main"
"mlx_lm.convert" = "mlx_lm.convert:main"
"mlx_lm.evaluate" = "mlx_lm.evaluate:main"
"mlx_lm.fuse" = "mlx_lm.fuse:main"
"mlx_lm.generate" = "mlx_lm.generate:main"
"mlx_lm.lora" = "mlx_lm.lora:main"
"mlx_lm.perplexity" = "mlx_lm.perplexity:main"
"mlx_lm.server" = "mlx_lm.server:main"
"mlx_lm.share" = "mlx_lm.share:main"
"mlx_lm.manage" = "mlx_lm.manage:main"
"mlx_lm.upload" = "mlx_lm.upload:main"

[dependency-groups]
dev = [
    "black",
    "isort",
    "pre-commit",
]

[tool.setuptools.dynamic]
version = { attr = "mlx_lm._version.__version__" }

[tool.setuptools]
include-package-data = false

[tool.setuptools.package-data]
mlx_lm = ["py.typed"]

[tool.setuptools.packages.find]
include = ["mlx_lm", "mlx_lm.*"]
namespaces = false
